image:
  file: .gitpod.dockerfile
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3001
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
tasks:
  - init: >
      (cp -n .env.example .env || true) &&
      psql -U gitpod -c 'CREATE DATABASE example;' &&
      psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d example &&
      ts-node ./docs/welcome.js 
  - command: >
      npm install &&
      npx prisma migrate dev --name init &&
      npm run dev &&
      npx prisma studio
      