image:
  file: .gitpod.dockerfile
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 3001
    onOpen: open-browser
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
tasks:
  - init: >
      (cp -n .env.example .env || true) && 
      echo "" >> .env && echo "BACKEND_URL=https://3001-${GITPOD_WORKSPACE_URL:8}" >> .env && 
      psql -U gitpod -c 'CREATE DATABASE example;' &&
      psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d example &&
      node ./docs/welcome.js 
      